- name: AWS CLI
  block:
    - name: Install AWS CLI
      ansible.builtin.command:
        argv:
          - uv
          - tool
          - install
          - --python=3.12
          - git+https://github.com/aws/aws-cli.git@v2
        creates: "{{ ansible_facts.user_dir }}/.local/bin/aws"
    - name: AWS Completer
      loop:
        - aws.fish
        - set.fish
      ansible.builtin.copy:
        src: fish/aws.fish
        dest: "{{ ansible_facts.user_dir }}/.config/fish/completions/{{ item }}"
        mode: u=rw,g=rw,o=r

- name: AWS SAM CLI
  block:
    - name: Install AWS SAM CLI
      ansible.builtin.command:
        argv:
          - uv
          - tool
          - install
          - aws-sam-cli
        creates: "{{ ansible_facts.user_dir }}/.local/bin/sam"
    - name: SAM Completion
      ansible.builtin.command:
        argv:
          - sam
        creates: "{{ ansible_facts.user_dir }}/.config/fish/completions/sam.fish"
      environment:
        _SAM_COMPLETE: fish_source
      register: fish_completions_aws_sam
    - name: SAM Completion File
      ansible.builtin.copy:
        content: "{{ fish_completions_aws_sam.stdout }}"
        dest: "{{ ansible_facts.user_dir }}/.config/fish/completions/sam.fish"
        mode: u=rw,g=rw,o=r
        force: false

- name: AWS CDK
  ansible.builtin.command:
    argv:
      - "{{ ansible_facts.user_dir }}/.local/share/mise/installs/pnpm/latest/pnpm"
      - install
      - --global
      - aws-cdk
    creates: "{{ ansible_facts.user_dir }}/.local/share/pnpm/cdk"
  environment:
    PNPM_HOME: "{{ ansible_facts.user_dir }}/.local/share/pnpm"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_facts.user_dir }}/.local/share/pnpm"

- name: AWS CodeCommit Git
  ansible.builtin.command:
    argv:
      - uv
      - tool
      - install
      - git-remote-codecommit
    creates: "{{ ansible_facts.user_dir }}/.local/bin/git-remote-codecommit"

- name: AWS Session Manager Plugin
  become: true
  ansible.builtin.apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb

- name: CloudFormation Lint
  ansible.builtin.command:
    argv:
      - uv
      - tool
      - install
      - cfn-lint
    creates: "{{ ansible_facts.user_dir }}/.local/bin/cfn-lint"

- name: AWS CLI - SSO-Profiles plugin
  block:
    - name: Create user local aws-cli venv
      ansible.builtin.command:
        argv:
          - python
          - -m
          - venv
          - "{{ ansible_facts.user_dir }}/.local/share/aws-cli-plugins"
        creates: "{{ ansible_facts.user_dir }}/.local/share/aws-cli-plugins"

    - name: Configure AWS CLI plugins path
      community.general.ini_file:
        path: "{{ ansible_facts.user_dir }}/.aws/config"
        mode: u=rw,g=,o=
        section: plugins
        option: cli_legacy_plugin_path
        value: "{{ ansible_facts.user_dir }}/.local/share/aws-cli-plugins"

    - name: Install SSO-Profiles plugin
      ansible.builtin.command:
        argv:
          - "{{ ansible_facts.user_dir }}/.local/share/aws-cli-plugins/bin/pip"
          - install
          - git+https://github.com/neilramsay/aws-cli-sso-profiles-plugin.git
        creates: "{{ ansible_facts.user_dir }}/.local/share/aws-cli-plugins/lib/python*/site-packages/aws_cli_sso_profiles_plugin"

    - name: Add SSO-Profiles plugin to Config
      community.general.ini_file:
        path: "{{ ansible_facts.user_dir }}/.aws/config"
        mode: u=rw,g=,o=
        section: plugins
        option: sso_profile
        value: aws_cli_sso_profiles_plugin.sso_profiles
