# - name: Debug
#   ansible.builtin.debug:
#     var: ansible_facts

- name: Set PATH
  environment:
    PATH: "{{ ansible_facts.user_dir }}/.local/bin:{{ ansible_env.PATH }}"
  block:
    - name: Make Local Bin
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.local/bin"
        mode: u=rwx,g=rwx,o=rx
        state: directory
    - name: Install and Configure Mise
      ansible.builtin.import_tasks: mise.yaml
    - name: Install/Configure Git
      ansible.builtin.import_tasks: git.yaml
    - name: Install Python
      ansible.builtin.import_tasks: python.yaml
    - name: Install Podman
      ansible.builtin.import_tasks: podman.yaml
    - name: Install Extras
      ansible.builtin.import_tasks: extras.yaml
    - name: Install Configure shell
      ansible.builtin.import_tasks: shell.yaml
    - name: Install AWS Tools
      ansible.builtin.import_tasks: aws.yaml
