- ansible.builtin.import_tasks: mise.yaml # noqa: name[missing]
- ansible.builtin.import_tasks: shell.yaml # noqa: name[missing]
- ansible.builtin.import_tasks: git.yaml # noqa: name[missing]
- ansible.builtin.import_tasks: python.yaml # noqa: name[missing]
