- name: Install Podman
  become: true
  ansible.builtin.apt:
    name:
      - podman
      - podman-docker
      - qemu-user-static
    state: present

- name: Podman Socket
  block:
    - name: Enable Podman User Socket
      ansible.builtin.systemd:
        scope: user
        name: podman.socket
        state: started
        enabled: true

    - name: Add Podman Socket env var
      ansible.builtin.command:
        argv:
          - mise
          - config
          - set
          - env.DOCKER_HOST
          - unix:///run/user/{{ ansible_facts.user_uid }}/podman/podman.sock
      changed_when: true

# yamllint disable rule:quoted-strings
- name: Install Dive
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/wagoodman/dive/releases/download/\
      v{{ development_dive_version }}/dive_{{ development_dive_version }}\
      _linux_amd64.deb"
# yamllint enable rule:quoted-strings

- name: Add Dive configuration
  ansible.builtin.copy:
    src: .dive.yaml
    dest: "{{ ansible_facts.user_dir }}/.dive.yaml"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: u=rw,g=r,o=r
