- name: Install Python 3.13 (global default) via Mise
  ansible.builtin.command:
    cmd: mise use -g python@3.13
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/share/mise/installs/python/3.13/bin/python3"

- name: Install Python 3.12 via Mise
  ansible.builtin.command:
    cmd: mise install python@3.12
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/share/mise/installs/python/3.12/bin/python3"

- name: Install Pipx via Mise
  ansible.builtin.command:
    cmd: mise use -y -g pipx@latest
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/share/mise/installs/pipx/latest/bin/pipx"

-

# echo 'fish_add_path --prepend $HOME/.local/bin' > ~/.config/fish/conf.d/path.fish
# source ~/.config/fish/conf.d/path.fish
# pipx install argcomplete
# register-python-argcomplete --shell fish pipx > ~/.config/fish/completions/pipx.fish
