- name: Install Python 3.13 (global default) via Mise
  ansible.builtin.command:
    cmd: mise use -g python@3.13
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/share/mise/installs/python/3.13/bin/python3"

- name: Install Python 3.12 via Mise
  ansible.builtin.command:
    cmd: mise install python@3.12
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/share/mise/installs/python/3.12/bin/python3"

- name: Install Pipx via Mise
  ansible.builtin.command:
    cmd: mise use -y -g pipx@latest
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/share/mise/installs/pipx/latest/bin/pipx"

- name: Install ArgComplete via Pipx
  ansible.builtin.command:
    cmd: mise exec pipx -- pipx install argcomplete
    creates:
      "{{ ansible_facts.user_dir }}/\
      .local/bin/register-python-argcomplete"

- name: Pipx Fish Completions
  ansible.builtin.copy:
    dest:
      "{{ ansible_facts.user_dir }}/\
      .config/fish/completions/pipx.fish"
    mode: u=rw,g=r=o=r
    content:
      "{{ lookup('pipe', '{{ ansible_facts.user_dir }}/.local/bin/register-python-argcomplete --shell fish pipx') }}"
