- name: Add ~/.local/bin to Fish Path
  ansible.builtin.copy:
    dest: "{{ ansible_facts.user_dir }}/\
      .config/fish/conf.d/path.fish"
    mode: u=rw,g=r,o=r
    content: fish_add_path --prepend $HOME/.local/bin

- name: Install LSD
  ansible.builtin.command:
    argv:
      - mise
      - use
      - -g
      - lsd
  changed_when: true

- name: Install LSD Fish Functions
  ansible.builtin.copy:
    src: fish/lsd.fish
    dest: "{{ ansible_facts.user_dir }}/.config/fish/conf.d/lsd.fish"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: u=rw,g=r,o=r
  changed_when: true
