- name: Add ~/.local/bin to Fish Path
  ansible.builtin.copy:
    dest: "{{ ansible_facts.user_dir }}/\
      .config/fish/conf.d/path.fish"
    mode: u=rw,g=r,o=r
    content: fish_add_path --prepend $HOME/.local/bin

- name: Update Fish History Command to show date+time
  ansible.builtin.copy:
    src: fish/history.fish
    dest: "{{ ansible_facts.user_dir }}/.config/fish/conf.d/history.fish"
    mode: u=rw,g=r,o=r

- name: LSD
  block:
    - name: Install LSD
      ansible.builtin.command:
        argv:
          - mise
          - use
          - --global
          - lsd
        creates: "{{ ansible_facts.user_dir }}/.local/share/mise/installs/lsd/latest/*/lsd"

    - name: LSD Completions
      block:
        - name: Locate LSD Completions
          ansible.builtin.find:
            paths:
              - "{{ ansible_facts.user_dir }}/.local/share/mise/installs/lsd/latest/"
            recurse: true
            patterns:
              - lsd.fish
          register: fish_completions_lsd_paths
        - name: Install LSD Completions
          loop:
            - lsd
            - ls
          ansible.builtin.copy:
            remote_src: true
            src: "{{ fish_completions_lsd_paths.files[0].path }}"
            dest: "{{ ansible_facts.user_dir }}/.config/fish/completions/{{ item }}.fish"
            mode: u=rw,g=r,o=r
        - name: Mangle LSD Completions for ls alias
          ansible.builtin.replace:
            path: "{{ ansible_facts.user_dir }}/.config/fish/completions/ls.fish"
            regexp: ^complete -c lsd
            replace: complete -c ls

- name: RipGrep
  block:
    - name: Install RipGrep
      ansible.builtin.command:
        argv:
          - mise
          - use
          - --global
          - ripgrep
        creates: "{{ ansible_facts.user_dir }}/.local/share/mise/installs/ripgrep/latest/*/rg"
    - name: RipGrep Completions
      block:
        - name: Locate RipGrep Completions
          ansible.builtin.find:
            paths:
              - "{{ ansible_facts.user_dir }}/.local/share/mise/installs/ripgrep/latest/"
            recurse: true
            patterns:
              - rg.fish
          register: fish_completions_ripgrep_paths
        - name: Install RipGrep Completions
          loop:
            - rg
            - grep
          ansible.builtin.copy:
            remote_src: true
            src: "{{ fish_completions_ripgrep_paths.files[0].path }}"
            dest: "{{ ansible_facts.user_dir }}/.config/fish/completions/{{ item }}.fish"
            mode: u=rw,g=r,o=r
        - name: Mangle RipGrep Completions for grep alias
          ansible.builtin.replace:
            path: "{{ ansible_facts.user_dir }}/.config/fish/completions/grep.fish"
            regexp: ^complete -c rg
            replace: complete -c grep
    - name: Install RipGrep Fish Functions
      ansible.builtin.copy:
        src: fish/rg.fish
        dest: "{{ ansible_facts.user_dir }}/.config/fish/conf.d/rg.fish"
        mode: u=rw,g=r,o=r
