- name: Install Terraform
  ansible.builtin.command:
    argv:
      - mise
      - use
      - --global
      - terraform
    creates: "{{ ansible_facts.user_dir }}/.local/share/mise/installs/terraform/latest/terraform"

- name: Install Terraform Lint
  ansible.builtin.command:
    argv:
      - mise
      - use
      - --global
      - tflint
    creates: "{{ ansible_facts.user_dir }}/.local/share/mise/installs/tflint/latest/tflint"
