- name: Update System Packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Remove Packages
  become: true
  ansible.builtin.apt:
    name: "{{ common_apt_packages_remove }}"
    state: absent
    purge: true

- name: Add Packages
  become: true
  ansible.builtin.apt:
    name: "{{ common_apt_packages_remove }}"
    state: present
    install_recommends: false
    purge: true
