- name: Update System Packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Remove Ubuntu Landscape, Pro Client, and Snap
  become: true
  ansible.builtin.apt:
    name:
      - ubuntu-pro-client
      - ubuntu-pro-client-l10n
      - landscape-client
      - landscape-common
      - snapd
    state: absent
    purge: true
    autoremove: true

- name: Install WSLu
  become: true
  ansible.builtin.apt:
    name: wslu

- name: Install Fish shell
  become: true
  ansible.builtin.apt:
    name: fish

- name: Install Extras
  become: true
  loop_control:
    loop_var: apt_extra
  loop:
    - ncdu
  ansible.builtin.apt:
    name: "{{ apt_extra }}"
    state: present
