- name: Update System Packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Remove Packages
  block:
    - name: List Packages to Remove
      ansible.builtin.debug:
        var: common_apt_packages_remove
    - name: Remove Packages
      become: true
      ansible.builtin.apt:
        name: "{{ common_apt_packages_remove }}"
        state: absent
        purge: true
        autoremove: true

- name: Add Packages
  block:
    - name: List Packages to Add
      ansible.builtin.debug:
        var: common_apt_packages_install
    - name: Add Packages
      become: true
      ansible.builtin.apt:
        name: "{{ common_apt_packages_install }}"
        state: present
        install_recommends: false
        purge: true
