- name: Apt
  ansible.builtin.import_tasks: apt.yaml

- name: Backup
  ansible.builtin.import_tasks: backup.yaml

- name: SystemD
  ansible.builtin.import_tasks: systemd-user.yaml

- name: Shell
  ansible.builtin.import_tasks: shell.yaml
