- name: Set user shells to fish
  become: true
  loop:
    - "{{ ansible_facts.user_id }}"
    - root
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/fish

- name: Make user fish directories
  ansible.builtin.command:
    argv:
      - fish
      - -c
      - __fish_on_interactive
    creates: "{{ ansible_facts.user_dir }}/.config/fish"
