- name: Set user shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    shell: /usr/bin/fish

- name: Set root user shell to fish
  become: true
  ansible.builtin.user:
    name: root
    shell: /usr/bin/fish
